name: Build Ubuntu Touch

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Make build.sh executable
      run: chmod +x ./build.sh

    - name: Run build.sh with bd option
      run: ./build.sh -b bd

    - name: Upload bd folder
      uses: actions/upload-artifact@v4
      with:
        path: bd/tmp/*
